name: Rename Template Repository
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: kota65535/github-template-rename-action@v1
        with:
          from-name: projectname
          paths-ignore: |
            .github/**

      - uses: kota65535/github-template-rename-action@v1
        with:
          from-name: ProjectName
          paths-ignore: |
            .github/**

