name: Rename Template Repository

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: kota65535/github-template-rename-action@v1
        with:
          from-name: project-name
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths-ignore: |
            .github/**
